export const AcpMethod = {
  sessionNew: "session/new",
  sessionLoad: "session/load",
  sessionResume: "session/resume",
  sessionList: "session/list",
  sessionPrompt: "session/prompt",
  sessionCancel: "session/cancel",
  sessionSetMode: "session/set_mode",
} as const;

export const MustangMethod = {
  commandsList: "_mustang.agent/commands/list",
  sessionActivateSkill: "_mustang.agent/session/activate_skill",
  sessionExecuteShell: "_mustang.agent/session/execute_shell",
  sessionExecutePython: "_mustang.agent/session/execute_python",
  sessionCancelExecution: "_mustang.agent/session/cancel_execution",
  sessionExecutionUpdate: "_mustang.agent/session/execution_update",
  sessionRename: "_mustang.agent/session/rename",
  sessionArchive: "_mustang.agent/session/archive",
  sessionDelete: "_mustang.agent/session/delete",
  sessionGetUsage: "_mustang.agent/session/get_usage",
  modelProfileList: "_mustang.agent/model/profile_list",
  modelProviderList: "_mustang.agent/model/provider_list",
  modelSetCurrent: "_mustang.agent/model/set_current",
  modelAdd: "_mustang.agent/model/add",
  modelUpdate: "_mustang.agent/model/update",
  webFetchBackendOptions: "_mustang.agent/web_fetch/backend_options",
  webFetchSetBackend: "_mustang.agent/web_fetch/set_backend",
  webFetchGetConfig: "_mustang.agent/web_fetch/get_config",
  webFetchSetConfig: "_mustang.agent/web_fetch/set_config",
  runtimeStatus: "_mustang.agent/runtime/status",
  runtimeRestart: "_mustang.agent/runtime/restart",
} as const;
