"""Mustang Agent Control Plane primitives.

The control plane is Mustang-owned. ACP and ACPX inform the vocabulary, but
this package must not depend on an external ACPX runtime.
"""

from kernel.agent_hub.contracts.control_plane import (
    ACP_METHOD_BY_OPERATION,
    MUSTANG_METHOD_BY_OPERATION,
    AgentControlOperation,
    AgentIdentity,
    AgentQueueState,
    AgentRuntimeController,
    AgentRuntimeKind,
    AgentStatus,
    AgentTaskIdentity,
    ControlResult,
    RuntimeTarget,
    StatusSnapshot,
)
from kernel.agent_hub.contracts.schemas import (
    AGENT_CONTRACT_SCHEMA_VERSION,
    DEFAULT_AGENT_ROOT,
    PRIMARY_AGENT_ID,
    AgentBindings,
    AgentDefinition,
    AgentPolicy,
    AgentRegistrationRequest,
    AgentResources,
    AgentRole,
    AgentRuntimeDeclaration,
    AgentRuntimeRecord,
    BindingPlan,
    BindingPlanEntry,
    CallerIdentity,
    CallerIdentityKind,
    ManagementCall,
    ManagementCapability,
    PlatformBinding,
    RegistrationToken,
    RouterFrame,
    RouterFrameKind,
    RouterTarget,
    RoutingSnapshot,
    RoutingSnapshotEntry,
    agent_state_dir,
    default_primary_agent_definition,
)
from kernel.agent_hub.contracts.transport import HUB_FRAME_SCHEMA_VERSION, HubFrame, HubFrameType

__all__ = [
    "ACP_METHOD_BY_OPERATION",
    "AGENT_CONTRACT_SCHEMA_VERSION",
    "DEFAULT_AGENT_ROOT",
    "HUB_FRAME_SCHEMA_VERSION",
    "MUSTANG_METHOD_BY_OPERATION",
    "PRIMARY_AGENT_ID",
    "AgentBindings",
    "AgentControlOperation",
    "AgentDefinition",
    "AgentIdentity",
    "AgentPolicy",
    "AgentQueueState",
    "AgentRegistrationRequest",
    "AgentResources",
    "AgentRole",
    "AgentRuntimeController",
    "AgentRuntimeDeclaration",
    "AgentRuntimeKind",
    "AgentRuntimeRecord",
    "AgentStatus",
    "AgentTaskIdentity",
    "BindingPlan",
    "BindingPlanEntry",
    "CallerIdentity",
    "CallerIdentityKind",
    "ControlResult",
    "HubFrame",
    "HubFrameType",
    "ManagementCall",
    "ManagementCapability",
    "PlatformBinding",
    "RegistrationToken",
    "RouterFrame",
    "RouterFrameKind",
    "RouterTarget",
    "RuntimeTarget",
    "RoutingSnapshot",
    "RoutingSnapshotEntry",
    "StatusSnapshot",
    "agent_state_dir",
    "default_primary_agent_definition",
]
